AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1
  Exclude:
    - 'db/**/*'
Layout/EndOfLine:
  EnforcedStyle: lf # Windows
Layout/LineLength:
  Max: 120
Metrics/ParameterLists:
  Max: 5
  MaxOptionalParameters: 5
